# Generated by Django 3.2.x on 2024-08-13 12:00

from django.db import migrations, models
from django.contrib.postgres.fields import ArrayField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sources', ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('cluster_summaries', models.JSONField(blank=True, default=dict, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('questions', models.TextField(blank=True, null=True)),
                ('number_of_articles', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='Topic',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='_1nbox_ai.Topic'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('supabase_user_id', models.CharField(max_length=255)),
                ('plan', models.CharField(default='no plan', max_length=255)),
                ('negative_keywords', models.TextField(blank=True, null=True)),
                ('positive_keywords', models.TextField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.CharField(max_length=255)),
                ('language', models.CharField(default='English', max_length=255)),
                ('time_zone', models.CharField(default='Europe/Madrid', max_length=255)),
                ('weekday', models.CharField(blank=True, max_length=255, null=True)),
                ('t', models.CharField(blank=True, max_length=255, null=True)),
                ('t2', models.CharField(blank=True, max_length=255, null=True)),
                ('t3', models.CharField(blank=True, max_length=255, null=True)),
                ('t4', models.CharField(blank=True, max_length=255, null=True)),
                ('t5', models.CharField(blank=True, max_length=255, null=True)),
                ('last_run', models.IntegerField(blank=True, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('provider_token', models.CharField(blank=True, max_length=255, null=True)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('messaging_app', models.CharField(blank=True, max_length=255, null=True)),
                ('topics', models.JSONField(blank=True, default=list, null=True)),
                ('days_since', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
