# Generated by Django 5.0.1 on 2024-02-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_1nbox_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
