# Generated by Django 5.0.1 on 2024-02-03 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_1nbox_ai', '0002_user_provider_token_user_refresh_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduledtask',
            old_name='time',
            new_name='t',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='time',
            new_name='t',
        ),
    ]
