# Generated by Django 5.0.1 on 2024-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_1nbox_ai', '0003_rename_time_scheduledtask_t_rename_time_user_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider_refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
