# Generated by Django 5.0.1 on 2024-07-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_1nbox_ai', '0007_user_t2_user_t3_user_t4_user_t5_user_weekday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='t2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='t3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='t4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='t5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='weekday',
        ),
        migrations.AlterField(
            model_name='user',
            name='t',
            field=models.CharField(default='16:00:00', max_length=255),
        ),
    ]
